export const ADD_PALETTE = 'ADD_PALETTE'
export const EDIT_PALETTE = 'EDIT_PALETTE'
export const DELETE_PALETTE = 'DELETE_PALETTE'

export const ADD_SHADES = 'ADD_SHADES'
export const EDIT_SHADES = 'EDIT_SHADES'
export const DELETE_SHADES = 'DELETE_SHADES'
export const DELETE_ALL_SHADES = 'DELETE_ALL_SHADES'

export const EDIT_BACKGROUND = 'EDIT_BACKGROUND'

export const INIT_LABELS = 'INIT_LABELS'
export const ADD_LABEL = 'ADD_LABEL'
export const EDIT_LABEL = 'EDIT_LABEL'
export const DELETE_LABEL = 'DELETE_LABEL'
export const DELETE_ALL_LABELS = 'DELETE_ALL_LABELS'

export const SELECT_PALETTE = 'SELECT_PALETTE'
export const SELECT_COLOR = 'SELECT_COLOR'
export const SELECT_OVERLAY = 'SELECT_OVERLAY'

export const GEN_CONTRASTS = 'GEN_CONTRASTS'
export const UNSET_CONTRASTS = 'UNSET_CONTRASTS'